production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

  session_store: redis_store
  redis_host: redis
  redis_port: 6379
  redis_db_name: 0
  session_options:
    key: _redmine_session
    redis:
      host: redis     # docker-compose'daki servis adı
      port: 6379
      db: 0
      namespace: redmine:session
    expire_after: 28800  # 8 saat
    secure: true
    httponly: true

  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: localhost
      port: 25
      domain: localhost

  attachments_storage_path: /usr/src/redmine/files
  log_level: :debug