server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: redmine_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: redmine_logs
          instance: redmine1
          __path__: /var/log/redmine/redmine1/redmine.log
    pipeline_stages:
      - regex:
          expression: '^\[(?P<timestamp>.*?)\]\s+(?P<level>\w+)\s+(?P<message>.*)$'
      - labels:
          level:

  - job_name: redmine2_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: redmine_logs
          instance: redmine2
          __path__: /var/log/redmine/redmine2/redmine.log
    pipeline_stages:
      - regex:
          expression: '^\[(?P<timestamp>.*?)\]\s+(?P<level>\w+)\s+(?P<message>.*)$'
      - labels:
          level:

  - job_name: redmine3_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: redmine_logs
          instance: redmine3
          __path__: /var/log/redmine/redmine3/redmine.log
    pipeline_stages:
      - regex:
          expression: '^\[(?P<timestamp>.*?)\]\s+(?P<level>\w+)\s+(?P<message>.*)$'
      - labels:
          level:

  - job_name: nginx_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx_logs
          __path__: /var/log/nginx/access.log 