apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: d1a7a510-5659-4cff-9360-700791e06552
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "5s" 